

events {
	multi_accept on;
}

http
{
	# Redirect HTTP traffic to HTTPS.
	server {
		listen 80;
		server_name localhost;

		error_page 400 401 403 404 405 500 502 503 504 /error;

		location = /error {
			internal;
			default_type text/plain;
			return 400 "400 Bad Request jami siir code chwia\n";
		}

		return 301 https://$host$request_uri;
	}

	# HTTPS server.
	server {
		listen 443 ssl;
		server_name localhost;

		error_page 400 401 403 404 405 500 502 503 504 /error;

		location = /error {
			internal;
			default_type text/plain;
			return 400 "400 Bad Request jami siir code chwia\n";
		}

		ssl_certificate /etc/nginx/ssl/server.crt;
		ssl_certificate_key /etc/nginx/ssl/server.key;

		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_prefer_server_ciphers on;

		location / {
			return 200 "hello nginx\n";
			add_header Content-Type text/plain;
		}
	}
}





