




#first about the nginx config file
#nginx make is webserver 'like what 42 project where he handel the requises'
#we need to set up this server to handel http req and engrept it for the security HTTPS


# the maincontext or Global where we define the general setting for the server
#like process they will handel the request
worker_processes 1;

#the event block deal with the network connection
events{
	multi_accept on;
}

#here the global http setting defining on
http
{
	listen 88 ssl;

}


#about tls first we need the certificate and prv-key
