




# #first about the nginx config file
# #nginx make is webserver 'like what 42 project where he handel the requises'
# #we need to set up this server to handel http req and engrept it for the security HTTPS


# # the maincontext or Global where we define the general setting for the server
# #like process they will handel the request
# worker_processes 1;

# #the event block deal with the network connection
# events{
# 	multi_accept on;
# }

# #here the global http setting defining on
# http
# {
	
# 	server
# 	{
# 		listen 88 ssl;
# 		ssl_protocols TLSv1.3;
# 		ssl_certificate_key /etc/nginx/ssl/server.key ;
# 		ssl_certificate /etc/nginx/ssl/server.csr ;

# 	}
# 	root /public/index.html;

# }


# #about tls first we need the certificate and prv-key
worker_processes 1;

events {
    multi_accept on;
}

http {
    server {
        listen 88 ssl;
        server_name localhost;

        ssl_protocols TLSv1.3;
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        root /var/www/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}